#!/usr/bin/env bash
# setup-cam.sh — Bootstrap a Raspberry Pi Zero 2 W as an RTSP camera node.
# Run on-device: curl/scp this script to the Pi, then: sudo bash setup-cam.sh
# Or run remotely: ssh user@cam01 'sudo bash -s' < scripts/setup-cam.sh
set -euo pipefail

# ── Configurable defaults ────────────────────────────────────────────────────
MEDIAMTX_VERSION="v1.17.1"
STREAM_WIDTH="${STREAM_WIDTH:-1920}"
STREAM_HEIGHT="${STREAM_HEIGHT:-1080}"
STREAM_FPS="${STREAM_FPS:-15}"
STREAM_BITRATE="${STREAM_BITRATE:-2500000}"
RTSP_PORT="${RTSP_PORT:-8554}"
STREAM_PATH="${STREAM_PATH:-cam}"

# ── Helpers ──────────────────────────────────────────────────────────────────
info()  { printf '\n\033[1;34m>>> %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m  ✓ %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m  ⚠ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m  ✗ %s\033[0m\n' "$*"; exit 1; }

# ── Pre-flight checks ───────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || fail "Run this script as root (sudo bash setup-cam.sh)"

info "Phase 0 — System update"
apt-get update -qq
apt-get full-upgrade -y -qq
ok "System up to date"

# ── Camera check ─────────────────────────────────────────────────────────────
info "Phase 1 — Camera detection"

# Make sure camera_auto_detect and imx219 overlay are set
BOOT_CFG="/boot/firmware/config.txt"
if ! grep -q "^camera_auto_detect=1" "$BOOT_CFG" 2>/dev/null; then
    echo "camera_auto_detect=1" >> "$BOOT_CFG"
    warn "Added camera_auto_detect=1 to $BOOT_CFG"
fi
if ! grep -q "^dtoverlay=imx219" "$BOOT_CFG" 2>/dev/null; then
    echo "dtoverlay=imx219" >> "$BOOT_CFG"
    warn "Added dtoverlay=imx219 to $BOOT_CFG (required on Trixie)"
fi

# Try detecting the camera
if rpicam-hello --list-cameras 2>&1 | grep -q "No cameras"; then
    warn "No camera detected."
    warn "Troubleshooting:"
    warn "  1. Power off, reseat the CSI ribbon cable (contacts toward the PCB on both ends)"
    warn "  2. Make sure you're using the 22-pin-to-22-pin cable (not the 15-pin Pi 4 cable)"
    warn "  3. Reboot and re-run this script"
    warn ""
    warn "Continuing setup anyway — camera can be connected later."
    CAMERA_OK=false
else
    rpicam-hello --list-cameras 2>&1
    ok "Camera detected"
    CAMERA_OK=true
fi

# ── Install dependencies ─────────────────────────────────────────────────────
info "Phase 2 — Install dependencies"
apt-get install -y -qq ffmpeg python3-venv python3-pip
ok "ffmpeg + python3 installed"

# ── Install MediaMTX ─────────────────────────────────────────────────────────
info "Phase 3 — Install MediaMTX ${MEDIAMTX_VERSION}"

MEDIAMTX_URL="https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VERSION}/mediamtx_${MEDIAMTX_VERSION}_linux_arm64.tar.gz"
MEDIAMTX_TMP=$(mktemp -d)

if [[ -f /usr/local/bin/mediamtx ]]; then
    ok "MediaMTX binary already present, skipping download"
else
    info "Downloading MediaMTX..."
    wget -q --show-progress -O "$MEDIAMTX_TMP/mediamtx.tar.gz" "$MEDIAMTX_URL"
    tar -xzf "$MEDIAMTX_TMP/mediamtx.tar.gz" -C "$MEDIAMTX_TMP"
    install -m 755 "$MEDIAMTX_TMP/mediamtx" /usr/local/bin/mediamtx
    ok "MediaMTX installed to /usr/local/bin/mediamtx"
fi

# ── Configure MediaMTX ───────────────────────────────────────────────────────
info "Phase 4 — Configure MediaMTX"

mkdir -p /etc/mediamtx
cat > /etc/mediamtx/mediamtx.yml <<YAML
###############################################
# MediaMTX config — generated by setup-cam.sh
###############################################

# Network
rtspAddress: :${RTSP_PORT}
rtpAddress: :8000
rtcpAddress: :8001

# Logging
logLevel: warn

# Paths
paths:
  ${STREAM_PATH}:
    source: rpiCamera
    rpiCameraWidth: ${STREAM_WIDTH}
    rpiCameraHeight: ${STREAM_HEIGHT}
    rpiCameraFPS: ${STREAM_FPS}
    rpiCameraBitrate: ${STREAM_BITRATE}
    rpiCameraCodec: auto
YAML

ok "Config written to /etc/mediamtx/mediamtx.yml"

# ── Systemd unit for MediaMTX ────────────────────────────────────────────────
info "Phase 5 — Create systemd service"

cat > /etc/systemd/system/mediamtx.service <<UNIT
[Unit]
Description=MediaMTX RTSP server
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/mediamtx /etc/mediamtx/mediamtx.yml
Restart=always
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable mediamtx.service
ok "mediamtx.service enabled"

# Start MediaMTX if camera is available
if [[ "$CAMERA_OK" == "true" ]]; then
    systemctl restart mediamtx.service
    sleep 2
    if systemctl is-active --quiet mediamtx.service; then
        ok "MediaMTX is running"
        LOCAL_IP=$(hostname -I | awk '{print $1}')
        ok "Stream available at: rtsp://${LOCAL_IP}:${RTSP_PORT}/${STREAM_PATH}"
    else
        warn "MediaMTX failed to start — check: journalctl -u mediamtx"
    fi
else
    warn "Skipping MediaMTX start (no camera). Start manually after connecting camera:"
    warn "  sudo systemctl start mediamtx"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
info "Setup complete!"
LOCAL_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "  Hostname:    $(hostname)"
echo "  IP:          ${LOCAL_IP}"
echo "  RTSP URL:    rtsp://${LOCAL_IP}:${RTSP_PORT}/${STREAM_PATH}"
echo "  Camera:      $( [[ "$CAMERA_OK" == "true" ]] && echo "detected" || echo "NOT detected — reseat cable & reboot" )"
echo "  Service:     sudo systemctl status mediamtx"
echo "  Logs:        journalctl -u mediamtx -f"
echo ""
echo "  Test from another machine:"
echo "    ffplay rtsp://${LOCAL_IP}:${RTSP_PORT}/${STREAM_PATH}"
echo "    vlc rtsp://${LOCAL_IP}:${RTSP_PORT}/${STREAM_PATH}"
echo ""
